<Strong> Fixed size time-series which we slide in time to predict into future. </Strong>

In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("../../../cryptoData/BTC_15m_data.csv")

In [10]:
df

date      open      high       low     close  \
0       2017-08-17 04:00:00   4261.48   4280.56   4261.48   4261.48   
1       2017-08-17 04:15:00   4261.48   4270.41   4261.32   4261.45   
2       2017-08-17 04:30:00   4280.00   4310.07   4267.99   4310.07   
3       2017-08-17 04:45:00   4310.07   4313.62   4291.37   4308.83   
4       2017-08-17 05:00:00   4308.83   4328.69   4304.31   4304.31   
...                     ...       ...       ...       ...       ...   
155486  2022-01-28 14:45:00  36684.11  36828.38  36600.00  36759.65   
155487  2022-01-28 15:00:00  36759.65  37198.00  36682.24  37149.99   
155488  2022-01-28 15:15:00  37150.00  37300.00  36925.89  36988.91   
155489  2022-01-28 15:30:00  36985.43  37115.32  36874.46  37022.42   
155490  2022-01-28 15:45:00  37023.86  37271.54  37000.34  37231.02   

             volume  
0          2.189061  
1          9.119865  
2         21.923552  
3         13.948531  
4          5.101153  
...             ...  
155486   560.007760  
155487   649.317780  
155488  1061.113920  
155489   452.420950  
155490   254.796250  

[155491 rows x 6 columns]

In [40]:
float_data = df.values[:, 1: ,].astype(float)
print(float_data)

[[4.26148000e+03 4.28056000e+03 4.26148000e+03 4.26148000e+03
  2.18906100e+00]
 [4.26148000e+03 4.27041000e+03 4.26132000e+03 4.26145000e+03
  9.11986500e+00]
 [4.28000000e+03 4.31007000e+03 4.26799000e+03 4.31007000e+03
  2.19235520e+01]
 ...
 [3.71500000e+04 3.73000000e+04 3.69258900e+04 3.69889100e+04
  1.06111392e+03]
 [3.69854300e+04 3.71153200e+04 3.68744600e+04 3.70224200e+04
  4.52420950e+02]
 [3.70238600e+04 3.72715400e+04 3.70003400e+04 3.72310200e+04
  2.54796250e+02]]


In [41]:
data = float_data[:,3,]
print(data)

[ 4261.48  4261.45  4310.07 ... 36988.91 37022.42 37231.02]


In [42]:
def rolling_window(train_data , window_size , predict_future_steps):
    for i in range (len(train_data) - window_size - predict_future_steps + 1):
        
        split_train = train_data[i:window_size+i]
        split_val = train_data[i+window_size:window_size+i+predict_future_steps]
        
        yield split_train , split_val

In [43]:
rolling = rolling_window(data , 4 , 1)

In [44]:
for train , val in rolling:
    print(train)
    print('vals')
    print(val)

[4261.48 4261.45 4310.07 4308.83]
vals
[4304.31]
[4261.45 4310.07 4308.83 4304.31]
vals
[4320.]
[4310.07 4308.83 4304.31 4320.  ]
vals
[4291.37]
[4308.83 4304.31 4320.   4291.37]
vals
[4315.32]
[4304.31 4320.   4291.37 4315.32]
vals
[4330.]
[4320.   4291.37 4315.32 4330.  ]
vals
[4311.02]
[4291.37 4315.32 4330.   4311.02]
vals
[4345.45]
[4315.32 4330.   4311.02 4345.45]
vals
[4324.35]
[4330.   4311.02 4345.45 4324.35]
vals
[4316.62]
[4311.02 4345.45 4324.35 4316.62]
vals
[4291.38]
[4345.45 4324.35 4316.62 4291.38]
vals
[4300.]
[4324.35 4316.62 4291.38 4300.  ]
vals
[4349.99]
[4316.62 4291.38 4300.   4349.99]
vals
[4360.71]
[4291.38 4300.   4349.99 4360.71]
vals
[4360.7]
[4300.   4349.99 4360.71 4360.7 ]
vals
[4360.69]
[4349.99 4360.71 4360.7  4360.69]
vals
[4360.69]
[4360.71 4360.7  4360.69 4360.69]
vals
[4360.]
[4360.7  4360.69 4360.69 4360.  ]
vals
[4360.]
[4360.69 4360.69 4360.   4360.  ]
vals
[4436.51]
[4360.69 4360.   4360.   4436.51]
vals
[4444.]
[4360.   4360.   4436.51 4444.  ]

[4027.   4026.99 3918.8  4022.74]
vals
[4025.]
[4026.99 3918.8  4022.74 4025.  ]
vals
[4027.51]
[3918.8  4022.74 4025.   4027.51]
vals
[4027.05]
[4022.74 4025.   4027.51 4027.05]
vals
[4029.06]
[4025.   4027.51 4027.05 4029.06]
vals
[3950.]
[4027.51 4027.05 4029.06 3950.  ]
vals
[4025.04]
[4027.05 4029.06 3950.   4025.04]
vals
[4025.04]
[4029.06 3950.   4025.04 4025.04]
vals
[4019.52]
[3950.   4025.04 4025.04 4019.52]
vals
[4019.52]
[4025.04 4025.04 4019.52 4019.52]
vals
[4055.7]
[4025.04 4019.52 4019.52 4055.7 ]
vals
[4039.1]
[4019.52 4019.52 4055.7  4039.1 ]
vals
[4036.09]
[4019.52 4055.7  4039.1  4036.09]
vals
[4039.09]
[4055.7  4039.1  4036.09 4039.09]
vals
[4039.1]
[4039.1  4036.09 4039.09 4039.1 ]
vals
[4041.1]
[4036.09 4039.09 4039.1  4041.1 ]
vals
[4031.87]
[4039.09 4039.1  4041.1  4031.87]
vals
[4016.]
[4039.1  4041.1  4031.87 4016.  ]
vals
[4010.]
[4041.1  4031.87 4016.   4010.  ]
vals
[4016.]
[4031.87 4016.   4010.   4016.  ]
vals
[4008.48]
[4016.   4010.   4016.   4008.48]


vals
[4220.38]
[4194.   4221.   4208.   4220.38]
vals
[4211.05]
[4221.   4208.   4220.38 4211.05]
vals
[4216.07]
[4208.   4220.38 4211.05 4216.07]
vals
[4230.]
[4220.38 4211.05 4216.07 4230.  ]
vals
[4235.]
[4211.05 4216.07 4230.   4235.  ]
vals
[4230.]
[4216.07 4230.   4235.   4230.  ]
vals
[4193.5]
[4230.  4235.  4230.  4193.5]
vals
[4230.]
[4235.  4230.  4193.5 4230. ]
vals
[4205.87]
[4230.   4193.5  4230.   4205.87]
vals
[4230.]
[4193.5  4230.   4205.87 4230.  ]
vals
[4207.]
[4230.   4205.87 4230.   4207.  ]
vals
[4215.08]
[4205.87 4230.   4207.   4215.08]
vals
[4270.]
[4230.   4207.   4215.08 4270.  ]
vals
[4300.]
[4207.   4215.08 4270.   4300.  ]
vals
[4326.23]
[4215.08 4270.   4300.   4326.23]
vals
[4340.61]
[4270.   4300.   4326.23 4340.61]
vals
[4335.]
[4300.   4326.23 4340.61 4335.  ]
vals
[4310.66]
[4326.23 4340.61 4335.   4310.66]
vals
[4316.01]
[4340.61 4335.   4310.66 4316.01]
vals
[4333.58]
[4335.   4310.66 4316.01 4333.58]
vals
[4319.66]
[4310.66 4316.01 4333.58 4319.66

[4222.]
[4169.01 4257.3  4271.02 4222.  ]
vals
[4221.04]
[4257.3  4271.02 4222.   4221.04]
vals
[4269.99]
[4271.02 4222.   4221.04 4269.99]
vals
[4270.]
[4222.   4221.04 4269.99 4270.  ]
vals
[4285.43]
[4221.04 4269.99 4270.   4285.43]
vals
[4261.9]
[4269.99 4270.   4285.43 4261.9 ]
vals
[4297.09]
[4270.   4285.43 4261.9  4297.09]
vals
[4275.]
[4285.43 4261.9  4297.09 4275.  ]
vals
[4269.]
[4261.9  4297.09 4275.   4269.  ]
vals
[4252.7]
[4297.09 4275.   4269.   4252.7 ]
vals
[4240.02]
[4275.   4269.   4252.7  4240.02]
vals
[4242.96]
[4269.   4252.7  4240.02 4242.96]
vals
[4230.]
[4252.7  4240.02 4242.96 4230.  ]
vals
[4227.]
[4240.02 4242.96 4230.   4227.  ]
vals
[4256.]
[4242.96 4230.   4227.   4256.  ]
vals
[4258.21]
[4230.   4227.   4256.   4258.21]
vals
[4277.74]
[4227.   4256.   4258.21 4277.74]
vals
[4290.77]
[4256.   4258.21 4277.74 4290.77]
vals
[4332.05]
[4258.21 4277.74 4290.77 4332.05]
vals
[4288.07]
[4277.74 4290.77 4332.05 4288.07]
vals
[4291.69]
[4290.77 4332.05 4288.07 4

vals
[4724.71]
[4702.8  4679.79 4695.   4724.71]
vals
[4681.]
[4679.79 4695.   4724.71 4681.  ]
vals
[4685.72]
[4695.   4724.71 4681.   4685.72]
vals
[4697.]
[4724.71 4681.   4685.72 4697.  ]
vals
[4697.]
[4681.   4685.72 4697.   4697.  ]
vals
[4699.]
[4685.72 4697.   4697.   4699.  ]
vals
[4698.99]
[4697.   4697.   4699.   4698.99]
vals
[4683.41]
[4697.   4699.   4698.99 4683.41]
vals
[4724.89]
[4699.   4698.99 4683.41 4724.89]
vals
[4731.13]
[4698.99 4683.41 4724.89 4731.13]
vals
[4711.26]
[4683.41 4724.89 4731.13 4711.26]
vals
[4715.]
[4724.89 4731.13 4711.26 4715.  ]
vals
[4721.05]
[4731.13 4711.26 4715.   4721.05]
vals
[4717.43]
[4711.26 4715.   4721.05 4717.43]
vals
[4723.92]
[4715.   4721.05 4717.43 4723.92]
vals
[4725.]
[4721.05 4717.43 4723.92 4725.  ]
vals
[4725.]
[4717.43 4723.92 4725.   4725.  ]
vals
[4728.13]
[4723.92 4725.   4725.   4728.13]
vals
[4730.04]
[4725.   4725.   4728.13 4730.04]
vals
[4735.16]
[4725.   4728.13 4730.04 4735.16]
vals
[4735.96]
[4728.13 4730.04 47

[4129.46]
[4230.8  4228.74 4120.01 4129.46]
vals
[4068.85]
[4228.74 4120.01 4129.46 4068.85]
vals
[4036.52]
[4120.01 4129.46 4068.85 4036.52]
vals
[4015.03]
[4129.46 4068.85 4036.52 4015.03]
vals
[4057.89]
[4068.85 4036.52 4015.03 4057.89]
vals
[4025.]
[4036.52 4015.03 4057.89 4025.  ]
vals
[4023.95]
[4015.03 4057.89 4025.   4023.95]
vals
[4014.83]
[4057.89 4025.   4023.95 4014.83]
vals
[4015.88]
[4025.   4023.95 4014.83 4015.88]
vals
[4010.]
[4023.95 4014.83 4015.88 4010.  ]
vals
[4002.71]
[4014.83 4015.88 4010.   4002.71]
vals
[3972.53]
[4015.88 4010.   4002.71 3972.53]
vals
[3995.12]
[4010.   4002.71 3972.53 3995.12]
vals
[4040.16]
[4002.71 3972.53 3995.12 4040.16]
vals
[4112.28]
[3972.53 3995.12 4040.16 4112.28]
vals
[4115.03]
[3995.12 4040.16 4112.28 4115.03]
vals
[4126.01]
[4040.16 4112.28 4115.03 4126.01]
vals
[4152.29]
[4112.28 4115.03 4126.01 4152.29]
vals
[4220.]
[4115.03 4126.01 4152.29 4220.  ]
vals
[4203.67]
[4126.01 4152.29 4220.   4203.67]
vals
[4189.86]
[4152.29 4220.  

[4680.15 4670.45 4715.45 4690.77]
vals
[4691.57]
[4670.45 4715.45 4690.77 4691.57]
vals
[4691.61]
[4715.45 4690.77 4691.57 4691.61]
vals
[4690.]
[4690.77 4691.57 4691.61 4690.  ]
vals
[4622.73]
[4691.57 4691.61 4690.   4622.73]
vals
[4592.]
[4691.61 4690.   4622.73 4592.  ]
vals
[4614.49]
[4690.   4622.73 4592.   4614.49]
vals
[4600.5]
[4622.73 4592.   4614.49 4600.5 ]
vals
[4597.54]
[4592.   4614.49 4600.5  4597.54]
vals
[4604.27]
[4614.49 4600.5  4597.54 4604.27]
vals
[4601.01]
[4600.5  4597.54 4604.27 4601.01]
vals
[4636.81]
[4597.54 4604.27 4601.01 4636.81]
vals
[4642.08]
[4604.27 4601.01 4636.81 4642.08]
vals
[4616.]
[4601.01 4636.81 4642.08 4616.  ]
vals
[4640.97]
[4636.81 4642.08 4616.   4640.97]
vals
[4636.62]
[4642.08 4616.   4640.97 4636.62]
vals
[4636.]
[4616.   4640.97 4636.62 4636.  ]
vals
[4605.02]
[4640.97 4636.62 4636.   4605.02]
vals
[4605.05]
[4636.62 4636.   4605.02 4605.05]
vals
[4630.31]
[4636.   4605.02 4605.05 4630.31]
vals
[4630.31]
[4605.02 4605.05 4630.31 4630

vals
[4176.24]
[4178.6  4195.09 4189.06 4176.24]
vals
[4207.44]
[4195.09 4189.06 4176.24 4207.44]
vals
[4211.02]
[4189.06 4176.24 4207.44 4211.02]
vals
[4162.16]
[4176.24 4207.44 4211.02 4162.16]
vals
[4191.53]
[4207.44 4211.02 4162.16 4191.53]
vals
[4192.45]
[4211.02 4162.16 4191.53 4192.45]
vals
[4175.03]
[4162.16 4191.53 4192.45 4175.03]
vals
[4199.98]
[4191.53 4192.45 4175.03 4199.98]
vals
[4198.99]
[4192.45 4175.03 4199.98 4198.99]
vals
[4214.]
[4175.03 4199.98 4198.99 4214.  ]
vals
[4220.34]
[4199.98 4198.99 4214.   4220.34]
vals
[4230.5]
[4198.99 4214.   4220.34 4230.5 ]
vals
[4260.41]
[4214.   4220.34 4230.5  4260.41]
vals
[4307.]
[4220.34 4230.5  4260.41 4307.  ]
vals
[4280.09]
[4230.5  4260.41 4307.   4280.09]
vals
[4269.22]
[4260.41 4307.   4280.09 4269.22]
vals
[4256.02]
[4307.   4280.09 4269.22 4256.02]
vals
[4231.86]
[4280.09 4269.22 4256.02 4231.86]
vals
[4221.76]
[4269.22 4256.02 4231.86 4221.76]
vals
[4221.87]
[4256.02 4231.86 4221.76 4221.87]
vals
[4251.29]
[4231.86 4

[3300. 3330. 3280. 3289.]
vals
[3280.]
[3330. 3280. 3289. 3280.]
vals
[3360.02]
[3280.   3289.   3280.   3360.02]
vals
[3650.01]
[3289.   3280.   3360.02 3650.01]
vals
[3711.2]
[3280.   3360.02 3650.01 3711.2 ]
vals
[3603.9]
[3360.02 3650.01 3711.2  3603.9 ]
vals
[3780.]
[3650.01 3711.2  3603.9  3780.  ]
vals
[3738.]
[3711.2 3603.9 3780.  3738. ]
vals
[3608.06]
[3603.9  3780.   3738.   3608.06]
vals
[3720.]
[3780.   3738.   3608.06 3720.  ]
vals
[3830.]
[3738.   3608.06 3720.   3830.  ]
vals
[3735.]
[3608.06 3720.   3830.   3735.  ]
vals
[3695.]
[3720. 3830. 3735. 3695.]
vals
[3610.]
[3830. 3735. 3695. 3610.]
vals
[3565.01]
[3735.   3695.   3610.   3565.01]
vals
[3550.37]
[3695.   3610.   3565.01 3550.37]
vals
[3550.]
[3610.   3565.01 3550.37 3550.  ]
vals
[3530.]
[3565.01 3550.37 3550.   3530.  ]
vals
[3548.]
[3550.37 3550.   3530.   3548.  ]
vals
[3610.]
[3550. 3530. 3548. 3610.]
vals
[3637.]
[3530. 3548. 3610. 3637.]
vals
[3609.46]
[3548.   3610.   3637.   3609.46]
vals
[3560.09]
[3

[3926.02 3930.01 3965.01 3965.63]
vals
[3960.1]
[3930.01 3965.01 3965.63 3960.1 ]
vals
[3968.]
[3965.01 3965.63 3960.1  3968.  ]
vals
[3961.9]
[3965.63 3960.1  3968.   3961.9 ]
vals
[3961.31]
[3960.1  3968.   3961.9  3961.31]
vals
[3998.98]
[3968.   3961.9  3961.31 3998.98]
vals
[3980.15]
[3961.9  3961.31 3998.98 3980.15]
vals
[3960.01]
[3961.31 3998.98 3980.15 3960.01]
vals
[3959.03]
[3998.98 3980.15 3960.01 3959.03]
vals
[3990.]
[3980.15 3960.01 3959.03 3990.  ]
vals
[3965.06]
[3960.01 3959.03 3990.   3965.06]
vals
[3960.]
[3959.03 3990.   3965.06 3960.  ]
vals
[3930.22]
[3990.   3965.06 3960.   3930.22]
vals
[3927.89]
[3965.06 3960.   3930.22 3927.89]
vals
[3910.]
[3960.   3930.22 3927.89 3910.  ]
vals
[3890.01]
[3930.22 3927.89 3910.   3890.01]
vals
[3859.96]
[3927.89 3910.   3890.01 3859.96]
vals
[3889.99]
[3910.   3890.01 3859.96 3889.99]
vals
[3869.8]
[3890.01 3859.96 3889.99 3869.8 ]
vals
[3842.04]
[3859.96 3889.99 3869.8  3842.04]
vals
[3889.8]
[3889.99 3869.8  3842.04 3889.8 

[3732.46 3732.46 3698.39 3702.01]
vals
[3713.43]
[3732.46 3698.39 3702.01 3713.43]
vals
[3729.55]
[3698.39 3702.01 3713.43 3729.55]
vals
[3698.38]
[3702.01 3713.43 3729.55 3698.38]
vals
[3718.06]
[3713.43 3729.55 3698.38 3718.06]
vals
[3731.54]
[3729.55 3698.38 3718.06 3731.54]
vals
[3700.]
[3698.38 3718.06 3731.54 3700.  ]
vals
[3681.56]
[3718.06 3731.54 3700.   3681.56]
vals
[3680.66]
[3731.54 3700.   3681.56 3680.66]
vals
[3658.46]
[3700.   3681.56 3680.66 3658.46]
vals
[3651.3]
[3681.56 3680.66 3658.46 3651.3 ]
vals
[3641.9]
[3680.66 3658.46 3651.3  3641.9 ]
vals
[3646.29]
[3658.46 3651.3  3641.9  3646.29]
vals
[3647.7]
[3651.3  3641.9  3646.29 3647.7 ]
vals
[3641.62]
[3641.9  3646.29 3647.7  3641.62]
vals
[3628.26]
[3646.29 3647.7  3641.62 3628.26]
vals
[3630.]
[3647.7  3641.62 3628.26 3630.  ]
vals
[3606.95]
[3641.62 3628.26 3630.   3606.95]
vals
[3593.]
[3628.26 3630.   3606.95 3593.  ]
vals
[3600.5]
[3630.   3606.95 3593.   3600.5 ]
vals
[3589.64]
[3606.95 3593.   3600.5  3589.

[3800.   3776.21 3776.21 3787.  ]
vals
[3781.05]
[3776.21 3776.21 3787.   3781.05]
vals
[3772.]
[3776.21 3787.   3781.05 3772.  ]
vals
[3770.5]
[3787.   3781.05 3772.   3770.5 ]
vals
[3779.01]
[3781.05 3772.   3770.5  3779.01]
vals
[3791.99]
[3772.   3770.5  3779.01 3791.99]
vals
[3795.59]
[3770.5  3779.01 3791.99 3795.59]
vals
[3790.03]
[3779.01 3791.99 3795.59 3790.03]
vals
[3787.58]
[3791.99 3795.59 3790.03 3787.58]
vals
[3779.]
[3795.59 3790.03 3787.58 3779.  ]
vals
[3780.04]
[3790.03 3787.58 3779.   3780.04]
vals
[3875.31]
[3787.58 3779.   3780.04 3875.31]
vals
[3910.79]
[3779.   3780.04 3875.31 3910.79]
vals
[3937.75]
[3780.04 3875.31 3910.79 3937.75]
vals
[3900.02]
[3875.31 3910.79 3937.75 3900.02]
vals
[3888.32]
[3910.79 3937.75 3900.02 3888.32]
vals
[3921.]
[3937.75 3900.02 3888.32 3921.  ]
vals
[3910.01]
[3900.02 3888.32 3921.   3910.01]
vals
[3970.]
[3888.32 3921.   3910.01 3970.  ]
vals
[3945.24]
[3921.   3910.01 3970.   3945.24]
vals
[3945.24]
[3910.01 3970.   3945.24 3945

[4170.   4146.03 4147.01 4114.22]
vals
[4150.]
[4146.03 4147.01 4114.22 4150.  ]
vals
[4136.5]
[4147.01 4114.22 4150.   4136.5 ]
vals
[4149.99]
[4114.22 4150.   4136.5  4149.99]
vals
[4114.65]
[4150.   4136.5  4149.99 4114.65]
vals
[4136.25]
[4136.5  4149.99 4114.65 4136.25]
vals
[4136.66]
[4149.99 4114.65 4136.25 4136.66]
vals
[4129.99]
[4114.65 4136.25 4136.66 4129.99]
vals
[4150.]
[4136.25 4136.66 4129.99 4150.  ]
vals
[4137.09]
[4136.66 4129.99 4150.   4137.09]
vals
[4141.15]
[4129.99 4150.   4137.09 4141.15]
vals
[4184.98]
[4150.   4137.09 4141.15 4184.98]
vals
[4170.]
[4137.09 4141.15 4184.98 4170.  ]
vals
[4171.39]
[4141.15 4184.98 4170.   4171.39]
vals
[4173.15]
[4184.98 4170.   4171.39 4173.15]
vals
[4150.]
[4170.   4171.39 4173.15 4150.  ]
vals
[4142.]
[4171.39 4173.15 4150.   4142.  ]
vals
[4165.48]
[4173.15 4150.   4142.   4165.48]
vals
[4170.]
[4150.   4142.   4165.48 4170.  ]
vals
[4174.5]
[4142.   4165.48 4170.   4174.5 ]
vals
[4171.05]
[4165.48 4170.   4174.5  4171.05]


vals
[4454.98]
[4458.48 4421.82 4423.03 4454.98]
vals
[4452.87]
[4421.82 4423.03 4454.98 4452.87]
vals
[4460.02]
[4423.03 4454.98 4452.87 4460.02]
vals
[4446.23]
[4454.98 4452.87 4460.02 4446.23]
vals
[4449.]
[4452.87 4460.02 4446.23 4449.  ]
vals
[4424.01]
[4460.02 4446.23 4449.   4424.01]
vals
[4401.01]
[4446.23 4449.   4424.01 4401.01]
vals
[4407.]
[4449.   4424.01 4401.01 4407.  ]
vals
[4450.]
[4424.01 4401.01 4407.   4450.  ]
vals
[4449.02]
[4401.01 4407.   4450.   4449.02]
vals
[4450.01]
[4407.   4450.   4449.02 4450.01]
vals
[4462.]
[4450.   4449.02 4450.01 4462.  ]
vals
[4456.11]
[4449.02 4450.01 4462.   4456.11]
vals
[4475.96]
[4450.01 4462.   4456.11 4475.96]
vals
[4456.06]
[4462.   4456.11 4475.96 4456.06]
vals
[4470.]
[4456.11 4475.96 4456.06 4470.  ]
vals
[4456.11]
[4475.96 4456.06 4470.   4456.11]
vals
[4458.01]
[4456.06 4470.   4456.11 4458.01]
vals
[4470.]
[4470.   4456.11 4458.01 4470.  ]
vals
[4464.5]
[4456.11 4458.01 4470.   4464.5 ]
vals
[4419.03]
[4458.01 4470.   4

KeyboardInterrupt: 